### ISSUE TITLE
Scroll wheel causes the menu bar area to zoom in

### ISSUE THREAD

**Issue by Phil-DS** [jsme-editor/jsme-editor.github.io#17]
One annoying problem with JSME is that, if the mouse is hovering over any part of the menu bars, and you use the scroll wheel, it causes it to zoom in. This can be a pain when working with JSME, as the bars can zoom in, and there doesn't seem to be a way to disable it, without disabling the zoom potential of the draw area, or excessive CSS/JS overriding the scroll events of the individual menu items.

To reproduce: Hover the mouse on any part of the JSME outer menu bars, and use the scroll wheel to scroll.

![image](https://user-images.githubusercontent.com/15893857/133063552-e4ada2bb-3923-4c64-b79f-e655e21f4625.png)

**Comment by jsme-editor** [comment]
> One annoying problem with JSME is that, if the mouse is hovering over any part of the menu bars, and you use the scroll wheel, it causes it to zoom in. 

The GUI and the drawing area can be zoomed in and out separately. I don't see why this can be an annoying problem. It is easy to reverse the zoom in of the GUI area with the mouse wheel. Could you describe a scenario or use of the editor where this problem occurs?

> and there doesn't seem to be a way to disable it, without disabling the zoom potential of the draw area

If requested, we could easily  add a new option to disable the zooming of the GUI part only.


Bruno Bienfait

**Comment by Phil-DS** [comment]
The main scenario is usually accidental scrolling. I've encountered it a few times when using it, and it unfortunately doesn't have a way to remove the zooming, so it becomes a hassle when having to the correct the window, without having to refresh the page. Having an option to disable the zooming on the GUI parts only would be very useful.
