### ISSUE TITLE
"move selected atom useful when drawing crowded structures" button 

### ISSUE THREAD

**Issue by sivunnat** [jsme-editor/jsme-editor.github.io#18]
I have a problem with the drawing of some molecules since there is no "move selected atom useful when drawing crowded structures" button on my pop-up JSME Structure Editor window. Why I can not see this icon? what should I do to see it?

**Comment by radusuciu** [comment]
What version are you using?

**Comment by jsme-editor** [comment]
Older versions of JSME do not have the "atommovebutton" option or did not have it enabled by default.  If you are using a recent version, try to add  the option "atommovebutton" or remove the option "noatommovebutton" if used.
