### ISSUE TITLE
how to send a smiles to the editor in javascript ?

### ISSUE THREAD

**Issue by thegodone** [jsme-editor/jsme-editor.github.io#19]
I wonder if I can send a SMILES in the editor for rendering. If I have already an instance of the editor how can I change molecule display ? 
I don't see an example except the openchemlib is it the only solution ?

**Comment by radusuciu** [comment]
I think what you're looking for is the `readGenericMolecularInput` function. Example:

```javascript
const jsmeApplet = new window.JSApplet.JSME(id, '300px', '300px')
jsmeApplet.readGenericMolecularInput('CC')
```
