### ISSUE TITLE
Error encountered when importing NPM package: "__propertyErrorFunction is not defined"

### ISSUE THREAD

**Issue by radusuciu** [jsme-editor/jsme-editor.github.io#21]
Here is an example:

https://codepen.io/radusuciu/pen/RwjRWMV

I've encountered this error locally (ie. not on codepen as well). I suspect that this may be a packaging issue and not a bug with JSME but I'm wondering if you've come across this before. Unfortunately there's not much info about his exact error on the internet.

Thanks for maintaining this wonderful library!

**Comment by jsme-editor** [comment]
I think also this is a packaging error from Skypack. I don't plan to investigate it further. Thank you for reporting this issue.
