### ISSUE TITLE
2 Warnings, (probably deprecated code)

### ISSUE THREAD

**Issue by ggieling** [jsme-editor/jsme-editor.github.io#23]
When using JSME in a webpage I receive two warnings related to (probably) deprecated code. The warnings are:
1) This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. jsme.nocache.js:24:206
2) Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead. See [description at mozilla](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Errors/Deprecated_source_map_pragma?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default)

If it is truly deprecated code, you may wish to adjust this before it becomes forbidden code.

**Comment by jsme-editor** [comment]
Issue confirmed with Firefox and fixed. Thank you for the report.
