### ISSUE TITLE
Delete molecule using Delete key caused error

### ISSUE THREAD

**Issue by seongsangcho-hits** [jsme-editor/jsme-editor.github.io#25]
Deleting a molecule when there is only one molecule left on the canvas will cause an error.

 - > "Exception caught: (TypeError) : Cannot read properties of null (reading 'Q')"

**Comment by jsme-editor** [comment]
I can see the error when trying to delete the last atom of the single molecule on the canvas.

**Comment by inghylt** [comment]
We're experiencing the same problem in our project
