### ISSUE TITLE
Resetting of highlight via command seems broken

### ISSUE THREAD

**Issue by Phil-DS** [jsme-editor/jsme-editor.github.io#31]
From looking at the documentation the following should remove the highlights from the first molecule on the drawer

```js
resetHighlight() {
    jsmeApplet.resetAtomColors(1)
    jsmeApplet.resetBondColors(1)
  }
```

However, this seems to fail. Tried to reset it by overriding the highlights, but it doesn't work either (A grey highlighting overlaying the entire molecule, but the original blue highlights remain).

**Comment by jsme-editor** [comment]
Unfortunately, I cannot reproduce the issue you described.  My test file is https://jsme-editor.github.io/dist/JSME_atom_highlight_demo.html . jsmeApplet.resetAtomColors(1) should reset the background colors of the atoms of the first molecule. 

I changed this line in the test HTML file to use index of 1 instead of 0::

`<button type="button" onclick='jsmeApplet.resetAtomColors(1);'>Reset atom colors</button>`

And it worked as expected.

**Comment by Phil-DS** [comment]
I tried that, but it only works with highlights set via the set `setAtomBackground` command. If you set them via the highlighter, it fails to remove them. If you set some with the highlighter and some via setAtomBackground, only the setAtomBackground ones are removed, and the highlighter ones remain

**Comment by jsme-editor** [comment]
![Screenshot from 2023-02-13 22-00-15](https://user-images.githubusercontent.com/75544418/218573449-93f53984-87d6-4257-afff-af621e00415b.png)



If I set one atom background color using the drop down color menu, clicking on the "Reset atom colors" button does not reset the color of this atom. Is this what you mean?

**Comment by Phil-DS** [comment]
Yes, that's what I mean.

**Comment by jsme-editor** [comment]
The upcoming version of JSME will have a new function, resetAtomMarks() , that can be used to reset the marks of the atoms that have been set with the drop down color menu (starting options: marker,markermenu). Similarly, there will a  new function called  resetBondMarks().
![Screenshot from 2023-02-22 21-54-25](https://user-images.githubusercontent.com/75544418/220756744-63f83747-e415-478f-a934-9734f07d5753.png)

Notes:

The atom marker can be used to mark an atom with only one color. Atom marks can be exported and imported as atom maps  in SMILES or MOLFILE .
Atom background colors can be mixed (more than one color per atom, e.g. 1,3,1,4,1,5,1,6). They cannot be exported or imported. There is no GUI element to set the background colors.

**Comment by jsme-editor** [comment]
A new version of JSME has been released. Could you try and check if the proposed solution works for you?

**Comment by Phil-DS** [comment]
Works for my scenario. Thanks!
